# Generated by Django 6.1.1 on 2026-09-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_user_order_ticket_alter_movie_actors_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "movie_session"), name="unique_row_seat_session"
            ),
        ),
    ]
